[tool.poetry]
name = "wingarc1st-hackathon-server"
version = "0.1.0"
description = ""
authors = ["Furuta Naoki <fn.nk.2002@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
